[project]
name = "ai-rust-programmer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.42.0",
    "loguru>=0.7.3",
    "openai>=1.58.1",
    "python-dotenv>=1.0.1",
]
